name: apertium-python CI Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        python3 setup.py install
        pipenv install --dev --system
    - name: Flake8 checks
      run: |
        flake8 --verbose apertium
    - name: mypy checks
      run: |
        mypy apertium --strict --any-exprs-report .mypy_coverage --ignore-missing-imports
        cat .mypy_coverage/any-exprs.txt
        coverage=$(tail -1 .mypy_coverage/any-exprs.txt | grep -Eo '[0-9\.]+%' | sed 's/%$//')
        if (( $(echo "$coverage < 95" | bc -l) )); then
            exit 1
        fi
    - name: code coverage and unittest
      run: |
        coverage run -m unittest --verbose --buffer tests
        coverage report --show-missing --fail-under 90 --include 'apertium/*'
